config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects do
    resources :to_dos, shallow: true
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :to_dos, dependent: :destroy

	validates :title, presence: true

	accepts_nested_attributes_for :to_dos, reject_if: :all_blank
end

app/models/to_do.rb
class ToDo < ApplicationRecord
	belongs_to :project

	validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
    #render json: @projects
  end

  def new
    @project = Project.new
    @project.to_dos.new
  end

  def show; end

  def create 
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
      flash[:notice] = "Задача успешно сохранена"
    else
      render :new
      flash[:notice] = "Задача не сохранилась"
    end
  end

  def edit; end 

  def update
    @project.update(project_params)  
  end

  def destroy
    if @project.delete
      redirect_to projects_path
      flash[:notice] = "Задача успешно удалена"
    else
      flash[:notice] = "Задача не удалена"
    end

  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, to_dos_attributes: [:id, :text, :is_completed, :_destroy])
  end

end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController

	def destroy
		@to_do = ToDo.find(params[:id])
		@to_do.destroy
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav_bar" %>
    <%= yield %>
  </body>
</html>

app/views/projects/_project.html.slim
h5
  =project.title
br

-project.to_dos.each do |t|
  .todo id="todo-#{t.id}"
    - if t.is_completed?
      .text-decoration-line-through
        li= t.text
    -else
      li= t.text
    p= link_to "Удалить пункт", to_do_path(t), method: :delete, remote: true

br

p=link_to "Редактировать", '#', class: "edit-project-link", data: { project_id: project.id }
p=link_to "Удалить Задачу", project_path(project), method: :delete

.project-errors
  =render 'shared/errors', resource: project

= form_with model: project, local: false, class: 'hidden ', html: { id: "edit-project-#{project.id}" } do |f|
  p
    = f.label :title, 'Задача'
    = f.text_area :title, placeholder: 'задача'

  p ToDo:
  p
    = f.fields_for :to_dos do |todo|
      = render 'projects/to_dos_fields', f: todo
    .links
      = link_to_add_association 'Добавить пункт', f, :to_dos, partial: 'projects/to_dos_fields'

  p= f.submit 'Сохранить'

app/views/projects/_to_dos_fields.html.slim
.nested-fields
  .field
    = f.label :text, "Сделать"
    = f.text_field :text
    br
    = f.label :is_completed, "Исполнено/Неисполнено"
    = f.check_box :is_completed

  = link_to_remove_association "Удалить пункт", f

app/views/projects/index.html.slim
h1(class="text text-center") Задачи

- @projects.each do |project|
  div(class="row row-cols-1 row-cols-md-2 g-4")
    div(class="col")
      div(class="card mb-3" style="max-width: 40rem;")
        div(class="card-body")
          h5(class="card-title")
            = project.title
          p(class="card-text")
            -project.to_dos.each do |todo|
              - if todo.is_completed?
                .text-decoration-line-through
                  = todo.text
              -else
                = todo.text
                br
            p= link_to "Показать", project_path(project)

app/views/projects/new.html.slim
h1 Новая Задача

=render 'shared/errors', resource: @project

= form_with model: @project, local: true do |f|
  p
    = f.label :title, "Задача"
    = f.text_field :title

  p
    = f.fields_for :to_dos do |todo|
      = render 'to_dos/to_dos_fields', f: todo
    .links
      = link_to_add_association 'Добавить пункт', f, :to_dos, partial: 'to_dos/to_dos_fields'


  p= f.submit 'Создать'

p= link_to 'Назад к списку задач', projects_path

app/views/projects/show.html.slim
h1 Задача

.project
	= render @project

=link_to 'К списку задач', projects_path

app/views/projects/update.js.erb
$('.project-errors').html("<%= render 'shared/errors', resource: @project %>");

<% if !@project.errors.present? %>
  $('.project').html('<%= j render @project %>');
<% end %>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  div= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_nav_bar.html.slim
nav(class="nav justify-content-end navbar navbar-expand-lg navbar-light bg-info")
  div(class='conteiner-fluid')
    h3= link_to "Новая Задача", new_project_path

app/views/to_dos/_to_dos_fields.html.slim
.nested-fields
  .field
    = f.label :text, "Сделать"
    = f.text_field :text
    br
    = f.label :is_completed, "Исполнено/Неисполнено"
    = f.check_box :is_completed

app/views/to_dos/destroy.js.erb
$('#todo-<%= @to_do.id %>').remove()